### PR TITLE
enable AVX_VNNI_INT8 instruction for qs8-qc8w-gemm/igemm

### PR DESCRIPTION
**Pull request by xujuntwt95329**
The new `AVX_VNNI_INT8` instruction can avoid XOR operation in qs8-qc82 gemm/igemm kernel, resulting ~3% performance improvement on mobilenet v1 and v2 int8 models. 

``` bash
-------------------------------------------------------------------------------------------------------
Benchmark                                                       Time       CPU     Iterations
-------------------------------------------------------------------------------------------------------
qs8_qc8w_gemm_5x8c8__avxvnni_prfm/mobilenet_v1/real_time       3356 us   3305 us      208  <-- orig
qs8_qc8w_gemm_5x8c8__avxvnniint8_prfm/mobilenet_v1/real_time   3249 us   3255 us      216  <-- avxvnniint8
-------------------------------------------------------------------------------------------------------
qs8_qc8w_gemm_5x8c8__avxvnni_prfm/mobilenet_v2/real_time       2783 us   2739 us      251  <-- orig
qs8_qc8w_gemm_5x8c8__avxvnniint8_prfm/mobilenet_v2/real_time   2674 us   2684 us      262  <-- avxvnniint8
```

### CODE REVIEW

**Review by fbarchard — CHANGES_REQUESTED** [review]
Looks good, but missing source templates:
scripts/generate-qs8-gemm.sh
scripts/generate-qs8-igemm.sh
src/qs8-gemm/MRx8c8-avxvnni.c.in
src/qs8-igemm/MRx8c8-avxvnni.c.in

**Comment by xujuntwt95329** [comment]
> Looks good, but missing source templates: scripts/generate-qs8-gemm.sh scripts/generate-qs8-igemm.sh src/qs8-gemm/MRx8c8-avxvnni.c.in src/qs8-igemm/MRx8c8-avxvnni.c.in

Thanks for reviewing the PR, I've updated these files, could you help have a look again?

**Review by fbarchard — APPROVED** [review]

**Comment by xujuntwt95329** [comment]
Resolved conflicts and re-submitted a new PR:
https://github.com/google/XNNPACK/pull/6990

**Comment by xujuntwt95329** [comment]
Already merged in https://github.com/google/XNNPACK/pull/6990

**Pull request closed without merging**
