### PR TITLE
 Added create and setup function for mod kernel

### PR DESCRIPTION
**Pull request by carrycooldude**
> I made a P.R for mod kernel in the [include file](https://github.com/google/XNNPACK/blob/master/include/xnnpack.h) for which I create an issue[ #1612](https://github.com/google/XNNPACK/issues/1612)

### CODE REVIEW

**Comment by carrycooldude** [comment]
cc: @huningxin

**Review by Maratyszcza — CHANGES_REQUESTED** [review]
Missing implementation

**Comment by carrycooldude** [comment]
@Maratyszcza I updated it in the include folder of xnnpack.h file

**Review by carrycooldude — COMMENTED** [review]
I hope so I update the xnnpack.h file let me know what I am doing wrong

**Comment by Maratyszcza** [comment]
I see the declaration of the new functions in `xnnpack.h`, but the implementation of the functions is missing. In general, I suggest to start with microkernels for the new operators, and only add operator-level APIs once you have microkernels for a full set of platforms supported by XNNPACK (i.e. x86, ARM, and WebAssembly).

**Review by carrycooldude — COMMENTED** [review]
Have a look over this.

**Comment by carrycooldude** [comment]
cc : @Maratyszcza

**Comment by Maratyszcza** [comment]
The code defines new functionality, but doesn't implement it. It is missing the implementation of the new functions declared in `xnnpack.h`.

**Comment by carrycooldude** [comment]
> The code defines new functionality, but doesn't implement it. It is missing the implementation of the new functions declared in `xnnpack.h`.

Actually The main implementation is in the tfjs kernel and for implementation I implemented on form of test suite 
And after this I am wrong let me know where I have to implement the function

**Comment by Maratyszcza** [comment]
If you implement this function in TF.js, you don't need it in XNNPACK. TF.js WAsm backend uses XNNPACK for perf-critical operators, not the other way around.

**Comment by carrycooldude** [comment]
I tired in that but test fails so I think it's better to do in XNNPACK
directly

**Pull request closed without merging**
