### PR TITLE
Add f32 Gavgpool RVV implementation microkernels, tests and config changes.

### PR DESCRIPTION
**Pull request by KaustubhIMG**

### CODE REVIEW

**Comment by KaustubhIMG** [comment]
@fbarchard @allenkelly @bhbruce @keeranroth, If you have time, please help review this PR.

**Review by fbarchard — APPROVED** [review]
Looks okay, thanks but we plan to refactor gavgpool to use 'rdsum' so dont spend too much time on the existing avgpool/maxpool etc.

**Comment by KaustubhIMG** [comment]
Do we plan to merge this PR?

**Comment by KaustubhIMG** [comment]
@allenkelly can you merge this PR?

**Pull request merged**
