### PR TITLE
Add qs8 c4 microkernels for wasmsdot

### PR DESCRIPTION
**Pull request by yolanda15**
Add qs8 c4 wasmsdot templates which can perform better than the default configuration.

The new template helps generate more effecient AVX-256 revectorized code with very few inserts at run time. See AVX-256 revectorization at [chromium bug](https://issues.chromium.org/issues/42202660).

Tested on Raptor Lake-P.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/ychen41/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/ychen41/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">

Benchmark | Time | CPU | Iterations |
-- | -- | -- | -- |
Default (Turbofan) |   |   |  
qs8_qc8w_gemm_4x16c4__wasmusdot/mobilenet_v1/real_time | 9941 | 9941 | 702
qs8_qc8w_gemm_4x16c4__wasmusdot/mobilenet_v2/real_time | 7219 | 7219 | 966
qs8_qc8w_gemm_4x16c4__wasmusdot_u2/mobilenet_v1/real_time | 8734 | 8734 | 801
qs8_qc8w_gemm_4x16c4__wasmusdot_u2/mobilenet_v2/real_time | 6706 | 6706 | 1044
qs8_qc8w_gemm_4x16c4__wasmusdot_u2_acc2/mobilenet_v1/real_time | 14519 | 14519 | 481
qs8_qc8w_gemm_4x16c4__wasmusdot_u2_acc2/mobilenet_v2/real_time | 9993 | 9993 | 700
qs8_qc8w_gemm_4x8c8__wasmusdot_u2/mobilenet_v1/real_time | 9412 | 9412 | 742
qs8_qc8w_gemm_4x8c8__wasmusdot_u2/mobilenet_v2/real_time | 7462 | 7462 | 938
qs8_qc8w_gemm_5x8c8__wasmusdot_u2/mobilenet_v1/real_time | 8742 | 8742 | 801
qs8_qc8w_gemm_5x8c8__wasmusdot_u2/mobilenet_v2/real_time | 7161 | 7161 | 978
  |   |   |  
Turboshaft |   |   |  
qs8_qc8w_gemm_4x16c4__wasmusdot/mobilenet_v1/real_time | 9242 | 9242 | 749
qs8_qc8w_gemm_4x16c4__wasmusdot/mobilenet_v2/real_time | 6637 | 6637 | 1047
qs8_qc8w_gemm_4x16c4__wasmusdot_u2/mobilenet_v1/real_time | 8395 | 8395 | 833
qs8_qc8w_gemm_4x16c4__wasmusdot_u2/mobilenet_v2/real_time | 6273 | 6273 | 1116
qs8_qc8w_gemm_4x16c4__wasmusdot_u2_acc2/mobilenet_v1/real_time | 11648 | 11648 | 601
qs8_qc8w_gemm_4x16c4__wasmusdot_u2_acc2/mobilenet_v2/real_time | 8296 | 8296 | 843
qs8_qc8w_gemm_4x8c8__wasmusdot_u2/mobilenet_v1/real_time | 8777 | 8777 | 797
qs8_qc8w_gemm_4x8c8__wasmusdot_u2/mobilenet_v2/real_time | 6763 | 6763 | 1033
qs8_qc8w_gemm_5x8c8__wasmusdot_u2/mobilenet_v1/real_time | 8424 | 8424 | 831
qs8_qc8w_gemm_5x8c8__wasmusdot_u2/mobilenet_v2/real_time | 6712 | 6712 | 1043
  |   |   |  
Revec + turboshaft |   |   |  
qs8_qc8w_gemm_4x16c4__wasmusdot/mobilenet_v1/real_time | 5381 | 5381 | 1300
qs8_qc8w_gemm_4x16c4__wasmusdot/mobilenet_v2/real_time | 4508 | 4508 | 1553
qs8_qc8w_gemm_4x16c4__wasmusdot_u2/mobilenet_v1/real_time | 5355 | 5355 | 1308
qs8_qc8w_gemm_4x16c4__wasmusdot_u2/mobilenet_v2/real_time | 4492 | 4492 | 1558
qs8_qc8w_gemm_4x16c4__wasmusdot_u2_acc2/mobilenet_v1/real_time | 7136 | 7136 | 981
qs8_qc8w_gemm_4x16c4__wasmusdot_u2_acc2/mobilenet_v2/real_time | 5392 | 5392 | 1297
qs8_qc8w_gemm_4x8c8__wasmusdot_u2/mobilenet_v1/real_time | 7365 | 7365 | 950
qs8_qc8w_gemm_4x8c8__wasmusdot_u2/mobilenet_v2/real_time | 5719 | 5719 | 1225
qs8_qc8w_gemm_5x8c8__wasmusdot_u2/mobilenet_v1/real_time | 6316 | 6316 | 1108
qs8_qc8w_gemm_5x8c8__wasmusdot_u2/mobilenet_v2/real_time | 5185 | 5185 | 1351

</body>

</html>

### CODE REVIEW

**Comment by yolanda15** [comment]
@fbarchard Please help take a look. Thanks!

**Review by fbarchard — APPROVED** [review]

**Comment by fbarchard** [comment]
Usually the reads of a C8 kernel out perform a C4 kernel, so I'm suspecting you're spilling registers?
Consider c4s2 which is 4 element dot products with rotate of 4 within cell of 8 bytes.  Similar to c8, reading 8 channels of source, but instead of 2x wide, you can keep 1 vector wide and rotate 8 bytes by 4 (shufd) after the first dot product.

**Comment by yolanda15** [comment]
> Usually the reads of a C8 kernel out perform a C4 kernel, so I'm suspecting you're spilling registers? 

For C8 kernels, no spilling after AVX-256 revec, however we cannot correctly coalesce the more efficient loads on *w* due to the additional horizontal add on the result of a single dot product. E.g. we use shuffle to add pairs of the int32 result from a single vector and combined two vectors to one after the main loop:
    v128_t vacc0x0123 = wasm_i32x4_add(wasm_v32x4_shuffle(vacc0x01, vacc0x23, 0, 2, 4, 6), wasm_v32x4_shuffle(vacc0x01, vacc0x23, 1, 3, 5, 7));
    v128_t vacc0x4567 = wasm_i32x4_add(wasm_v32x4_shuffle(vacc0x45, vacc0x67, 0, 2, 4, 6), wasm_v32x4_shuffle(vacc0x45, vacc0x67, 1, 3, 5, 7));

Current for such statement, we will coalesce the vacc0x01 with vacc0x45 instead, which will cause the revec of vb01 with vb45 that are not continuous. So the revec result for C8 kernel is not as efficient as C4 kernel.

> Consider c4s2 which is 4 element dot products with rotate of 4 within cell of 8 bytes. Similar to c8, reading 8 channels of source, but instead of 2x wide, you can keep 1 vector wide and rotate 8 bytes by 4 (shufd) after the first dot product.

Ok, I will have a try on c4s2.

**Comment by yolanda15** [comment]
> Consider c4s2 which is 4 element dot products with rotate of 4 within cell of 8 bytes. Similar to c8, reading 8 channels of source, but instead of 2x wide, you can keep 1 vector wide and rotate 8 bytes by 4 (shufd) after the first dot product.

Tried 4x16c4s2 which improves WASM SIMD128 by ~3% on MobileNetV1, but not benefitial to AVX-256.
Also tried c4s4 and c4s8, both produced more register spills and regressions.

**Pull request merged**
