### PR TITLE
Reshape Softmax Output + Test

### PR DESCRIPTION
**Pull request by mcr229**
reshape softmax output

### CODE REVIEW

**Comment by mcr229** [comment]
can add tests to compare reshaped outputs with operator level APIs if necessary

**Comment by mcr229** [comment]
Can't add reviewers so tagging: @alankelly @digantdesai

**Comment by mcr229** [comment]
also please let me know if you want to seperate reshape tests into seperate file i.e. softmax-reshape-test. It seems like some other tests follow that i.e. abs-reshape-test, add-reshape-test

**Review by digantdesai — COMMENTED** [review]
lgtm, I will let Alan stamp it.

**Review by alankelly — APPROVED** [review]

**Review by alankelly — APPROVED** [review]

**Comment by alankelly** [comment]
Thanks for the changes. I'm getting a merge conflict. Can you git pull --rebase?

**Comment by alankelly** [comment]
Thanks for fixing all the model files.

**Pull request merged**
