### PR TITLE
Enable use of pre-built dependencies in arbitrary locations

### PR DESCRIPTION
**Pull request by iskunk**
This PR allows use of pre-built dependencies like cpuinfo and googletest in arbitrary locations with `XNNPACK_USE_SYSTEM_LIBS=ON`, similar to what is possible with their source trees currently.

For cpuinfo, pthreadpool, FXdiv, and FP16, this extends the existing `*_SOURCE_DIR` functionality slightly to allow the variable to specify an installed build rather than a source tree. (The variable name is not ideal for this purpose, but it may be considered a temporary measure until all four packages support the CMake standard `FIND_PACKAGE()` mechanism.)

For googletest and (google)benchmark, this makes use of their support for `FIND_PACKAGE()`. With CMP0074 enabled, it becomes possible to specify `-DGTest_ROOT=/path/to/googletest` and/or `-Dbenchmark_ROOT=/path/to/gbenchmark`.

Note that in order to use the imported google{test,benchmark} libraries, programs must link against their proper names: `GTest::gtest` instead of just `gtest`, `benchmark::benchmark` instead of `benchmark`, and so on. Linking against e.g. `gtest` leads to a plain `-lgtest` on the linker line, without a `-L/path/to/lib` directive or full path that would allow the linker to find the library.

----

The second commit fixes a related link error that occurs with `XNNPACK_USE_SYSTEM_LIBS=ON` and a static pthreadpool library:
```
[ 89%] Building C object CMakeFiles/operator-size-test.dir/test/operator-size.c.o
[ 89%] Linking CXX executable operator-size-test
libXNNPACK.a(init.c.o): In function `xnn_initialize':
/home/src/xnnpack/0.0-git20231130.3577502/src/init.c:74: undefined reference to `pthread_once'
libXNNPACK.a(hardware-config.c.o): In function `xnn_init_hardware_config':
/home/src/xnnpack/0.0-git20231130.3577502/src/configs/hardware-config.c:242: undefined reference to `pthread_once'
libXNNPACK.a(argmaxpool-config.c.o): In function `xnn_init_f32_argmaxpool_config':
/home/src/xnnpack/0.0-git20231130.3577502/src/configs/argmaxpool-config.c:164: undefined reference to `pthread_once'
libXNNPACK.a(avgpool-config.c.o): In function `xnn_init_f16_avgpool_config':
/home/src/xnnpack/0.0-git20231130.3577502/src/configs/avgpool-config.c:237: undefined reference to `pthread_once'
libXNNPACK.a(avgpool-config.c.o): In function `xnn_init_f32_avgpool_config':
/home/src/xnnpack/0.0-git20231130.3577502/src/configs/avgpool-config.c:250: undefined reference to `pthread_once'
libXNNPACK.a(avgpool-config.c.o):/home/src/xnnpack/0.0-git20231130.3577502/src/configs/avgpool-config.c:263: more undefined references to `pthread_once' follow
/home/pkg/pthreadpool/0.0-git20230829.4fe0e1e/lib/libpthreadpool.a(pthreads.c.o): In function `pthreadpool_create':
/home/src/pthreadpool/0.0-git20230829.4fe0e1e/src/pthreads.c:285: undefined reference to `pthread_create'
/home/pkg/pthreadpool/0.0-git20230829.4fe0e1e/lib/libpthreadpool.a(pthreads.c.o): In function `pthreadpool_destroy':
/home/src/pthreadpool/0.0-git20230829.4fe0e1e/src/pthreads.c:444: undefined reference to `pthread_join'
icpx: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [CMakeFiles/operator-size-test.dir/build.make:103: operator-size-test] Error 1
make[3]: Leaving directory '/tmp/xnnpack-build'
make[2]: *** [CMakeFiles/Makefile2:11436: CMakeFiles/operator-size-test.dir/all] Error 2
make[2]: Leaving directory '/tmp/xnnpack-build'
make[1]: *** [Makefile:146: all] Error 2
```

Because the CMake code is importing the bare pthreadpool (static) library, and not its dependencies, it needs to address the dependencies. All that is missing here is `-lpthread`/`-pthread`, which is obtained with `FIND_PACKAGE(Threads)`. Once pthreadpool itself supports `FIND_PACKAGE()`, this can be handled more cleanly.

I have tested both the download-deps and system-libs build modalities with these changes, and obtained a successful build and test-suite run from both.

### CODE REVIEW

**Review by alankelly — APPROVED** [review]

**Comment by iskunk** [comment]
Thanks @alankelly. The conflicts that have arisen are minor, but please let me know if you need me to push an update.

**Comment by alankelly** [comment]
Please rebase and if all open source builds pass, I'll merge it tomorrow.
Thanks

**Comment by iskunk** [comment]
Gladly, I've rebased and updated the PR. Both the download-deps and system-libs builds complete and test out clean, as before.

Note that there is now a third commit in the chain, intended to fix this newly-seen link error:
```
$ make f32-rminmax-test 
[  0%] Built target logging
[  0%] Built target fxdiv
[  0%] Built target fp16
[100%] Built target microkernels-all
[100%] Built target hardware-config
[100%] Linking CXX executable f32-rminmax-test
CMakeFiles/f32-rminmax-test.dir/test/f32-rminmax.cc.o: In function `F32_RMINMAX__AVX_U8_batch_eq_8_Test::TestBody()':
/tmp/XNNPACK/test/f32-rminmax.cc:535: undefined reference to `xnn_init_f32_default_avx_params'
CMakeFiles/f32-rminmax-test.dir/test/f32-rminmax.cc.o: In function `F32_RMINMAX__AVX_U8_batch_div_8_Test::TestBody()':
/tmp/XNNPACK/test/f32-rminmax.cc:543: undefined reference to `xnn_init_f32_default_avx_params'
CMakeFiles/f32-rminmax-test.dir/test/f32-rminmax.cc.o: In function `F32_RMINMAX__AVX_U8_batch_lt_8_Test::TestBody()':
/tmp/XNNPACK/test/f32-rminmax.cc:552: undefined reference to `xnn_init_f32_default_avx_params'
CMakeFiles/f32-rminmax-test.dir/test/f32-rminmax.cc.o: In function `F32_RMINMAX__AVX_U8_batch_gt_8_Test::TestBody()':
/tmp/XNNPACK/test/f32-rminmax.cc:561: undefined reference to `xnn_init_f32_default_avx_params'
CMakeFiles/f32-rminmax-test.dir/test/f32-rminmax.cc.o: In function `F32_RMINMAX__AVX_U16_ACC2_batch_eq_16_Test::TestBody()':
/tmp/XNNPACK/test/f32-rminmax.cc:572: undefined reference to `xnn_init_f32_default_avx_params'
CMakeFiles/f32-rminmax-test.dir/test/f32-rminmax.cc.o:/tmp/XNNPACK/test/f32-rminmax.cc:580: more undefined references to `xnn_init_f32_default_avx_params' follow
/usr/bin/ld: f32-rminmax-test: hidden symbol `xnn_init_f32_default_avx_params' isn't defined
/usr/bin/ld: final link failed: Bad value
icpx: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [CMakeFiles/f32-rminmax-test.dir/build.make:10054: f32-rminmax-test] Error 1
make[2]: *** [CMakeFiles/Makefile2:17941: CMakeFiles/f32-rminmax-test.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:17948: CMakeFiles/f32-rminmax-test.dir/rule] Error 2
make: *** [Makefile:6003: f32-rminmax-test] Error 2
```

**Comment by iskunk** [comment]
Looks like someone fixed that link error. Rebased again, back down to two commits.

**Pull request merged**
